### ISSUE TITLE
Return values for /property path

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/rda_collections_api#4]
The [spec](http://rdacollectionswg.github.io/apidocs/#!/Members/get_collections_id_members_mid_properties_property) describes a whole MemberItem as return value for a GET on properties. Is this desired? I could see this make sense on PUT or POST - receive the updated member - but for GET I would probably expect a single value (or object or array).

Thoughts?

**Comment by TobiasWeigel** [comment]
Yes, I agree that this is not consistent. Looking at the corresponding [PUT](http://rdacollectionswg.github.io/apidocs/#!/Members/put_collections_id_members_mid_properties_property) I am also not sure whether the memberItem record even makes sense there. Wouldn't I just call PUT on _one_ specific property, like ../properties/location? A PUT with the full MemberItem record would then only make sense for the root, /properties.

**Comment by balmas** [comment]
moving this issue to the spec repository.
